apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana-pvc
  labels:
    name: grafana-pvc

spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  
