apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: prometheus-pvc
  labels:
    name: prometheus-pvc

spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  
